### ISSUE TITLE
Change Hyper link for SYCL Specification Section  

### ISSUE THREAD

**Issue by imvucic** [KhronosGroup/SYCL_Reference#61]
From conf.py we can see current implementation of hyper link templates: 
```
prolog_template = string.Template(
    '.. _`SYCL Specification`: '
    + 'https://www.khronos.org/registry/SYCL/specs/sycl-2020-provisional.pdf'
```
This approach lead to user jump on first page of specs and manually search to appropriate section(e.g 4.6.2  Platform class).
Our recommendation should be to put hyper link only on section and jump directly to page equivalent to recommendation(e.g 4.6.2 -> page 59)  

Code example conf.py should be like :
`.. |SYCL_SPEC_HEADER_FILES| replace:: SYCL Specification `Section 4.3 <https://registry.khronos.org/SYCL/specs/sycl-2020-provisional.pdf#page=56&zoom=100,96,189>`__`

**Comment by mkinsner** [comment]
Would it make sense to link to the HTML version of the specification instead of PDF, where we can more easily jump to specific sections?

The existing content was for SYCL 1.2.1, where there was only a PDF specification (no HTML).  The HTML version is new with SYCL 2020, so probably makes sense to migrate all links to that more appropriate format.

**Comment by imvucic** [comment]
Hi @mkinsner,
Thanks for quick response. We are totally agree to switch to HTML version. Current work with header, namespaces and device selectors reworked. For the rest we will create separate story's in JIRA.

**Comment by imvucic** [comment]
Based on max_line length 79 and recommendation from https://github.com/KhronosGroup/SYCL_Reference/commit/03a29b03206a318da4b439bf9a776da7a01cfc81#diff-7fb09d9c93c5b9e807628c723d479e34bb753665a1cb1cbc1c3b09e4768789a5

we will proceed like :
```
sycl_ref_url = (
    "https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html"
)
prolog_template = string.Template(
    (
        f".. |SYCL_SPEC_HEADER_FILES| replace:: SYCL Specification "
        f"`Section 4.3 <{sycl_ref_url}#sec:headers-and-namespaces>`__"
        f"\n"
    )
    + (
        f".. |SYCL_SPEC_PLATFORM| replace:: SYCL Specification "
        f"`Section 4.6.2 <{sycl_ref_url}#sec:platform-class>`__"
        f"\n"
    )
    + f"""
```

**Comment by imvucic** [comment]
As we agree to use template from : https://github.com/KhronosGroup/SYCL_Reference/issues/61#issuecomment-1746458731
