### ISSUE TITLE
Constructors of the SYCL platform class

### ISSUE THREAD

**Issue by imvucic** [KhronosGroup/SYCL_Reference#67]
In the [Table 15](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#table.constructors.platform) we can see only two   
Constructors :
```
platform()
template <typename DeviceSelector> explicit platform(const DeviceSelector&)
```
Previous version of guide also present here Backend interoperability:
`explicit platform(cl_platform_id platformID);`

Do you prefer strict following new spec  [Table 15](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#table.constructors.platform) or you have something in addition?

**Comment by gmlueck** [comment]
We should follow Table 15 in the specification.  The old constructor `explicit platform(cl_platform_id platformID)` is an example of an old API that is no longer present in SYCL 2020.  These are exactly the type of thing that we want to remove the reference guide.

**Comment by imvucic** [comment]
Hi @gmlueck,
Thanks for clarification. We are going to follow [Table 15](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#table.constructors.platform) and remove unneeded parts.
