### ISSUE TITLE
[Future work] Add clickable list of sub-sections or members at top of each page

### ISSUE THREAD

**Issue by mkinsner** [KhronosGroup/SYCL_Reference#71]
This is a longer term item and can be automated.  I think we need a clickable list/table of the sections near the top of each page, more like what cppref has, to be able to quickly see what members exist without scrolling through the detailed descriptions.

Right now there is no summary, so scrolling is needed to get an overview.

![image](https://github.com/KhronosGroup/SYCL_Reference/assets/34314961/b10abf57-e4e4-4934-bc98-94889e059ab4)

**Comment by rscohn2** [comment]
In the doc's theme, navigation inside the page is in the column on the right. Not sure if this is what you were looking for.

<img width="929" alt="image" src="https://github.com/KhronosGroup/SYCL_Reference/assets/1936730/68189ca4-34d4-40cb-b1b0-0be1d1243417">

**Comment by mkinsner** [comment]
Thanks.  I see that nav list activate when I widen the window more.  So probably sufficient.
