### ISSUE TITLE
navigation_with_keys warning

### ISSUE THREAD

**Issue by PetroBondar** [KhronosGroup/SYCL_Reference#84]
We received failure in checks for the last PR:

![image](https://github.com/KhronosGroup/SYCL_Reference/assets/122783909/92091752-3a01-4f91-b2aa-c69b64c6d2a0)

Seems like navigation_with_keys is now by default set to **False**: https://github.com/pydata/pydata-sphinx-theme/issues/1492

Should we preserve the old behavior (set it explicitly to **True**)?

**Comment by rscohn2** [comment]
I recommend accepting the new default. Will setting to false clear the error?

**Comment by PetroBondar** [comment]
Yes, the warning disappears if we set it explicitly.

**Comment by PetroBondar** [comment]
The warning was resolved. I close the issue.
